FROM python:3.10

WORKDIR /usr/ap/src

COPY ./consumer.py ./
COPY ./producer.py ./

RUN pip install pulsar
# all optional components
RUN pip install 'pulsar-client[all]==3.3.0'

CMD ["sh", "-c", "python ./consumer.py & python ./producer.py"]